# Password Generator With Python

This application can be used to generate random passwords and save them all in a file if you want

## Execution

Use the python command to execute this file if you are using a terminal

```bash
python <file-address>
```

## Explanation

This program lets you choose the length of the password you want and generates a random password accordingly. If you entered any non valid length value it will keep asking you unitl you provide a valid value for password length. (Any letter, word, a negative number or any special character are non valid)

After that it will ask you whether you want to save this password in a file or not, you can press y or n and hit enter for stating  YES or NO respectively. It will then ask you for what purpose this password has been created for, so if you want come back and check for which website or app this password was made for you can do that easily by accessing the file generated by this program.

<b>(Please Note that if you a file named <b style="color: red">passwords.txt</b> in a directory where this python program is executed then please move that file to some another directory or rename that file)</b>

## Contributing
Pull requests are welcome. For major changes, please open an issue first to discuss what you would like to change.

## License
[MIT](https://choosealicense.com/licenses/mit/)
